apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulumi-blog-deployment
  #namespace: pulumi-blog
  labels:
    app: pulumi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pulumi
  template:
    metadata:
      labels:
        app: pulumi
    spec:
      containers:
      - name: pulumi
        image: 791433942247.dkr.ecr.eu-central-1.amazonaws.com/blog-repo:6fe4a16328f1ebdbc63645a63c7c16292ce7821a
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: regcred