apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulumi-blog-deployment
  labels:
    app: pulumi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pulumi
  template:
    metadata:
      labels:
        app: pulumi
    spec:
      containers:
      - name: pulumi
        image: 791433942247.dkr.ecr.eu-central-1.amazonaws.com/blog-repo:06103163cafe8a531076d2ea200aaeb699d7e137
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: regcred