name: Pulumi blog action 
on: [workflow_dispatch]
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
        #script: aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
      - name: Build, publish and deploy image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          - docker build -t $ECR_REGISTRY/$ECR_REGISTRY:$IMAGE_TAG /flask_app/Dockerfile
          - docker push $ECR_REGISTRY/$ECR_REGISTRY:$IMAGE_TAG
      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v3
        with:
          #command: destroy
          command: preview
          #command: up
          stack-name: DinoJelincic/eks-pulumi-blog/develop
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
