name: Pulumi blog action 
on: [workflow_dispatch]
env:
  DOCKER_REGISTRY: 791433942247.dkr.ecr.eu-central-1.amazonaws.com/blog-repo-945feee
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  APP_NAME: pulumi-blog-app
  NAME: pulumi-blog-app
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to ECR
        id: login-ecr
        uses: aws-action/amazon-ecr-login@v1
      - name: Build, publish and deploy image to ECR
        id: build-image
        run: |
          - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID .
          - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID
      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v3
        with:
          #command: destroy
          command: preview
          #command: up
          stack-name: DinoJelincic/eks-pulumi-blog/develop
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  docker:
    image: docker:latest
    stage: docker 
    services:
      - docker:19-dind
    before_script:
      - apk add --no-cache curl jq python3 py3-pip
      - pip install awscli
    script:
      - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
      - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID .
      - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID 